<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_UserManagement</name>
   <tag></tag>
   <elementGuidId>0731b4e9-1081-4446-9e31-d5658e852413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admin-user-management']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#admin-user-management</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de0a3a93-f1ce-4d46-a33a-e8de72fc3b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-user-management</value>
      <webElementGuid>82081459-5558-490d-baf9-5e3b76b16a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__SideBarMenuItemIconWrapper-sc-1992fy4-3 itUGak</value>
      <webElementGuid>69a4e666-5435-4d38-9a49-a7377b5376ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin-user-management&quot;)</value>
      <webElementGuid>967ff8a1-9056-44ce-ae7c-d9b55e6c0a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='admin-user-management']</value>
      <webElementGuid>2171260b-35f7-4d03-badf-aef0b3c75bef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
